version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: realtime_updates
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  python-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/realtime_updates
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend
      - ./client:/app/client

volumes:
  postgres_data: